import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { AccessPerformanceAvailabilityService } from '../src/domain.mjs';
import { AtomicStore } from '../src/store.mjs';

class MemoryStore { constructor() { this.database = { accessPerformanceAvailabilityReviews: [] }; this.writes = 0; } read() { return structuredClone(this.database); } write(data) { this.database = structuredClone(data); this.writes += 1; } }
const owner = { id: 'owner-848', role: 'evidence_owner' };
const input = { supplierId: 'SUP-848', evidenceReference: 'EVD-848', availabilityReference: 'AVL-848-ACCESS-01', availabilityScope: 'access_commitment_availability' };
const chain = [{ action: 'profileAvailability', role: 'availability_profile_analyst' }, { action: 'verifyCapacity', role: 'availability_capacity_verifier' }, { action: 'validateCommitment', role: 'availability_commitment_validator' }, { action: 'authorizeAvailability', role: 'availability_authority' }, { action: 'releaseAvailability', role: 'availability_registrar' }];

describe('AccessPerformanceAvailabilityService', () => {
  it('records the complete independently controlled availability lifecycle', () => { const store = new MemoryStore(); const service = new AccessPerformanceAvailabilityService(store); let record = service.submit(input, owner, 'request-submit-848'); for (const step of chain) record = service.transition(record.id, step.action, { note: step.action }, { id: step.role, role: step.role }, `request-${step.action}-848`); expect(record.status).toBe('availability_released'); expect(record.events.map((event) => event.type)).toContain('availability_released'); expect(store.writes).toBe(6); });
  it('rejects invalid input and invalid role or order without mutation', () => { const store = new MemoryStore(); const service = new AccessPerformanceAvailabilityService(store); expect(() => service.submit({ ...input, availabilityScope: 'other' }, owner, 'request-invalid-848')).toThrow('availability scope is invalid'); const record = service.submit(input, owner, 'request-state-848'); expect(() => service.transition(record.id, 'profileAvailability', { note: 'attempt' }, owner, 'request-role-848')).toThrow('role availability_profile_analyst is required'); expect(() => service.transition(record.id, 'validateCommitment', { note: 'order' }, { id: 'validator', role: 'availability_commitment_validator' }, 'request-order-848')).toThrow('access-performance availability review must be capacity_verified'); expect(store.writes).toBe(1); });
  it('rejects duplicate requests, missing records, and terminal transitions', () => { const store = new MemoryStore(); const service = new AccessPerformanceAvailabilityService(store); let record = service.submit(input, owner, 'request-repeat-848'); expect(() => service.transition(record.id, 'profileAvailability', { note: 'repeat' }, { id: 'profile', role: 'availability_profile_analyst' }, 'request-repeat-848')).toThrow('request identifier was already used'); expect(() => service.get('missing-848')).toThrow('access-performance availability review was not found'); for (const step of chain) record = service.transition(record.id, step.action, { note: step.action }, { id: step.role, role: step.role }, `terminal-${step.action}-848`); expect(() => service.transition(record.id, 'releaseAvailability', { note: 'retry' }, { id: 'registrar', role: 'availability_registrar' }, 'retry-release-848')).toThrow('access-performance availability review must be availability_authorized'); });
  it('recovers an absent availability data file', () => { const directory = mkdtempSync(join(tmpdir(), 'access-performance-availability-')); try { const store = new AtomicStore(join(directory, 'data', 'access-performance-availability-reviews.json')); expect(store.read()).toEqual({ accessPerformanceAvailabilityReviews: [] }); } finally { rmSync(directory, { recursive: true, force: true }); } });
});
